export const kProjectFileName = 'api-test-project.yaml'
export const kRequestDirName = 'request'
export const kResponseDirName = 'responses'
export const kSchemaFileName = 'schema.json'
export const kFullExampleFileName = 'full.test.json'